# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学习相关资料\密码学\code\wrok1\UI\tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(325, 368)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 193, 127))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.line_d = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.line_d.setContentsMargins(0, 0, 0, 0)
        self.line_d.setObjectName("line_d")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_text = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_text.setObjectName("label_text")
        self.horizontalLayout_2.addWidget(self.label_text)
        self.lineEdit_text = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_text.setObjectName("lineEdit_text")
        self.horizontalLayout_2.addWidget(self.lineEdit_text)
        self.line_d.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_key1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_key1.setObjectName("label_key1")
        self.horizontalLayout_3.addWidget(self.label_key1)
        self.lineEdit_key1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_key1.setObjectName("lineEdit_key1")
        self.horizontalLayout_3.addWidget(self.lineEdit_key1)
        self.line_d.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_key2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_key2.setEnabled(True)
        self.label_key2.setObjectName("label_key2")
        self.horizontalLayout_4.addWidget(self.label_key2)
        self.lineEdit_key2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_key2.setObjectName("lineEdit_key2")
        self.horizontalLayout_4.addWidget(self.lineEdit_key2)
        self.line_d.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_fill = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_fill.setObjectName("label_fill")
        self.horizontalLayout.addWidget(self.label_fill)
        self.lineEdit_fill = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_fill.setObjectName("lineEdit_fill")
        self.horizontalLayout.addWidget(self.lineEdit_fill)
        self.line_d.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(220, 20, 95, 65))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(30, 150, 256, 192))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_text.setText(_translate("Form", "原文"))
        self.label_key1.setText(_translate("Form", "密钥"))
        self.label_key2.setText(_translate("Form", "key2"))
        self.label_fill.setText(_translate("Form", "填充（单个字母）"))
        self.pushButton.setText(_translate("Form", "加密"))
        self.pushButton_2.setText(_translate("Form", "解密"))
